# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='TempFullName', max_length=255),
            preserve_default=False,
        ),
    ]
